name: dataform
description: A Flutter package to fetch data from a form as a Map.
version: 1.1.1
homepage: https://github.com/bianchettihugo/dataform

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
